# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HypeSocial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cards'
  pod 'Firebase/Core'  
  pod 'Firebase/Messaging'
# Pods for HypeSocial

  target 'HypeSocialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
